version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/api_data
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
volumes:
  api_data:
  db_data: