default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV['POSTGRES_DATABASE_NAME'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5432
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE_TEST_NAME'] %>

staging:
  <<: *default
  timeout: 5000

production:
  <<: *default
  timeout: 5000
